CONTIKI_PROJECT = yazici4
all: $(CONTIKI_PROJECT)

CFLAGS += -DCOFFEE_FILESYSTEM=1

CFLAGS += -DCOFFEE_CONF_SIZE=250000
CFLAGS += -DCOFFEE_CONF_SECTOR_SIZE=1024
CFLAGS += -DCOFFEE_CONF_NAME_LENGTH=16

CONTIKI = ../..
include $(CONTIKI)/Makefile.include

